exports.config = {
  port: '9515',
  path: '/',
  specs: ['./webdriverio/tests/*.js'],
  exclude: [],
  maxInstances: 10,
  capabilities: [{ browserName: 'chrome' }],
  sync: true,
  logLevel: 'silent',
  coloredLogs: true,
  deprecationWarnings: true,
  bail: 0,
  screenshotPath: './webdriverio/errorShots/',
  baseUrl: 'http://webdriverio.local',
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd'
  },
  services: ['chromedriver'],
  chromeDriverArgs: ['--port=9999'],
  chromeDriverLogs: './chromedriver',
}